/* ------------------------------------------------------------------------------
 *
 *     This code was generated by CGW X-Script Code Generator.
 *
 *     Archymeta Information Technologies Co., Ltd.
 *
 *     Changes to this file, especially those bit flags, may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * 
 ------------------------------------------------------------------------------ */

define(['knockout', 'config', 'model'], function (ko, config, model) {

    var c = function () {

        var self = this;

        childSelectedEntity = null;
        currentDisplayEntity = null;
        currentUpdatingEntity = null;
        currentSelectedSet = null;

        var EntityTabUpdating = false;
        var currEntityTabIndex = 0;
        var OKStr = 'OK';
        var CancelStr = 'Cancel';

        var updateEntityDetails = function () {
            $("#EntityDetails .Details .SetNav").accordion({
                collapsible: true,
                heightStyle: "auto"
            });
            $("#EntityDetails .Details .SetNav .ui-accordion-content").show();
            $("#EntityDetails .Details .SetNav button").button();
            $("#EntityDetails .Details .Tabs button").button();
            $("#EntityDetails .Details .Tabs").tabs({
                heightStyle: "auto",
                active: currEntityTabIndex,
                activate: function (event, ui) {
                    if (EntityTabUpdating) return;
                    currEntityTabIndex = ui.newTab.index();
                }
            }).css({
                'min-height': '220px',
                'overflow': 'auto'
            });;
            $(".resizeblock").on("click", function () {
                $(this).resizable({ aspectRatio: true });
            });
        }

        self.MaterializeOrderRef = function (data, event) {
            data.MaterializeOrderRef().done(function () {
                if (set !== null) {
                    for (var i = 0; i < set.CurrentPage().Items().length; i++) {
                        var e = set.CurrentPage().Items()[i];
                        if (e.OrderID() == data.OrderID() && e !== data) {
                            e.data.OrderRef = data.OrderRef();
                            e.OrderRef(e.data.OrderRef);
                            e.IsOrderRefMaterialized(true);
                        }
                    }
                }
                $(event.currentTarget).qtip({
                    overwrite: true,
                    content: data.OrderRef() ? data.OrderRef().DistinctString : 'null',
                    position: {
                        my: 'left bottom',
                        at: 'top left',
                        target: $(event.currentTarget)
                    },
                    show: {
                        event: 'none',
                        ready: true,
                        solo: true
                    },
                    hide: 'unfocus'
                });
                $(event.currentTarget).qtip('toggle', true);
            });
            event.stopPropagation();
            return false;
        }

        self.display_OrderRef = function (data, event) {
            $("#displayWindow").dialog('option', 'title', 'Order_Detail View');
            $("#displayWindow").dialog("open");
            if (!data.IsOrderRefMaterialized()) {
                data.MaterializeOrderRef().done(function () {
                    $("#displayFrame")[0].src = '../Order/LoadEntityView?OrderID=' + data.OrderID();
                });
            } else {
                $("#displayFrame")[0].src = '../Order/LoadEntityView?OrderID=' + data.OrderID();
            }
        }

        self.select_OrderID = function (data, event) {
            var selBtns = {};
            selBtns[OKStr] = function () { 
                OrderID_selected();
                $(this).dialog('close');
            }
            selBtns[CancelStr] = function () { 
                childSelectedEntity = null; 
                $(this).dialog('close');
            };
            $("#selectWindow").dialog('option', 'title', 'Order View');    
            $("#selectWindow").dialog('option', 'buttons', selBtns);    
            $("#selectWindow").dialog("open");
            currentUpdatingEntity = data;
            if (data.data !== null) {
                $("#selectFrame")[0].src = '../Order/SelectView?filter=' + encodeURIComponent('OrderID !== ' + data.OrderID());
            } else {
                $("#selectFrame")[0].src = '../Order/SelectView?filter=';
            }
            event.stopPropagation();
            return false;
        }

        var OrderID_selected = function () {
            if (currentUpdatingEntity !== null && childSelectedEntity !== null) {
                currentUpdatingEntity.OrderID(childSelectedEntity.OrderID());
            }
        }

        self.MaterializeProductRef = function (data, event) {
            data.MaterializeProductRef().done(function () {
                if (set !== null) {
                    for (var i = 0; i < set.CurrentPage().Items().length; i++) {
                        var e = set.CurrentPage().Items()[i];
                        if (e.ProductID() == data.ProductID() && e !== data) {
                            e.data.ProductRef = data.ProductRef();
                            e.ProductRef(e.data.ProductRef);
                            e.IsProductRefMaterialized(true);
                        }
                    }
                }
                $(event.currentTarget).qtip({
                    overwrite: true,
                    content: data.ProductRef() ? data.ProductRef().DistinctString : 'null',
                    position: {
                        my: 'left bottom',
                        at: 'top left',
                        target: $(event.currentTarget)
                    },
                    show: {
                        event: 'none',
                        ready: true,
                        solo: true
                    },
                    hide: 'unfocus'
                });
                $(event.currentTarget).qtip('toggle', true);
            });
            event.stopPropagation();
            return false;
        }

        self.display_ProductRef = function (data, event) {
            $("#displayWindow").dialog('option', 'title', 'Order_Detail View');
            $("#displayWindow").dialog("open");
            if (!data.IsProductRefMaterialized()) {
                data.MaterializeProductRef().done(function () {
                    $("#displayFrame")[0].src = '../Product/LoadEntityView?ProductID=' + data.ProductID();
                });
            } else {
                $("#displayFrame")[0].src = '../Product/LoadEntityView?ProductID=' + data.ProductID();
            }
        }

        self.select_ProductID = function (data, event) {
            var selBtns = {};
            selBtns[OKStr] = function () { 
                ProductID_selected();
                $(this).dialog('close');
            }
            selBtns[CancelStr] = function () { 
                childSelectedEntity = null; 
                $(this).dialog('close');
            };
            $("#selectWindow").dialog('option', 'title', 'Product View');    
            $("#selectWindow").dialog('option', 'buttons', selBtns);    
            $("#selectWindow").dialog("open");
            currentUpdatingEntity = data;
            if (data.data !== null) {
                $("#selectFrame")[0].src = '../Product/SelectView?filter=' + encodeURIComponent('ProductID !== ' + data.ProductID());
            } else {
                $("#selectFrame")[0].src = '../Product/SelectView?filter=';
            }
            event.stopPropagation();
            return false;
        }

        var ProductID_selected = function () {
            if (currentUpdatingEntity !== null && childSelectedEntity !== null) {
                currentUpdatingEntity.ProductID(childSelectedEntity.ProductID());
            }
        }

    }
    return c;
})