/* ------------------------------------------------------------------------------
 *
 *     This code was generated by CGW X-Script Code Generator.
 *
 *     Archymeta Information Technologies Co., Ltd.
 *
 *     Changes to this file, especially those bit flags, may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * 
 ------------------------------------------------------------------------------ */

define(['knockout', 'config', 'model'], function (ko, config, model) {

    var c = function (dt) {

        var self = this;
        self.set =  typeof dt !== 'undefined' && typeof dt.CreateSet !== 'undefined' ? dt.CreateSet() : null;
        self.MaterializeCustomerDemographicRef = function (data, event) {
            data.MaterializeCustomerDemographicRef().done(function () {

            }).fail(function(jqxhr, textStatus, error) {
                if (typeof config.alert === 'function') {
                    config.alert(jqxhr.statusText + '\r\n\r\n' + jqxhr.responseText);
                } else {
                    alert(jqxhr.statusText + '\r\n\r\n' + jqxhr.responseText);
                }
            });
        };

        self.MaterializeCustomerRef = function (data, event) {
            data.MaterializeCustomerRef().done(function () {

            }).fail(function(jqxhr, textStatus, error) {
                if (typeof config.alert === 'function') {
                    config.alert(jqxhr.statusText + '\r\n\r\n' + jqxhr.responseText);
                } else {
                    alert(jqxhr.statusText + '\r\n\r\n' + jqxhr.responseText);
                }
            });
        };

        self.initialize = function (CustomerID, CustomerTypeID) {
            pageMgr.loadedModelTable['service-clients/scripts/Northwind/models/sets/CustomerCustomerDemo'] = model;
            if (self.set == null)
                self.set = new model.entitySet();
            return self.set.LoadEntityByKey(CustomerID, CustomerTypeID, true);
        };
    }
    return c;
})