/* ------------------------------------------------------------------------------
 *
 *     This code was generated by CGW X-Script Code Generator.
 *
 *     Archymeta Information Technologies Co., Ltd.
 *
 *     Changes to this file, especially those bit flags, may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * 
 ------------------------------------------------------------------------------ */

define(['knockout', 'config', 'queryModels' ], function (ko, config, q) {

    var CategoryView = function (data) {
        var self = this;
        self.IsViewModel = true;
        self.data = data;
        self.DistinctString = data !== null ? data.DistinctString : "";
        self.LookupQuery = data !== null ? "?CategoryID=" + self.data.CategoryID : "";

        self.CreateSet = function () {
            return new CategorySet();
        };

        self.CategoryID = data.CategoryID;
        self.CategoryName = data.CategoryName;
        self.Description = data.Description;
        self.IsDescriptionLoaded = ko.observable(data.IsDescriptionLoaded);

        self.LoadEntityDescription = function () {
            if (self.IsDescriptionLoaded()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/LoadEntityDescription",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID })
            }).pipe(
                function (data) {
                    if (data !== null) {
                        self.Description(data);
                    }
                    self.IsDescriptionLoaded(true);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.Picture = data.Picture;
        self.IsPictureLoaded = ko.observable(data.IsPictureLoaded);

        self.LoadEntityPicture = function () {
            if (self.IsPictureLoaded()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/LoadEntityPicture",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID })
            }).pipe(
                function (data) {
                    if (data !== null) {
                        self.Picture(data);
                    }
                    self.IsPictureLoaded(true);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.IsEntityIdentical = function (data) {
            if (typeof data == 'undefined' || data == null || typeof data.IsViewModel == 'undefined' || self.IsViewModel !== data.IsViewModel ) {
                return false;
            }
            return self.CategoryID == data.CategoryID;
        };

        self.DescriptionQuery = 'load-delayed-Description?CategoryID=' + self.data.CategoryID + '&contentType=text/plain';

        self.PictureQuery = 'load-delayed-Picture?CategoryID=' + self.data.CategoryID + '&contentType=image/bmp';

        self.IsAllProductsMaterialized = ko.observable(false);
        if (data.Products == null) {
            self.Products = ko.observable(null);
            self.IsProductsMaterialized = ko.observable(false);
        } else {
            self.IsProductsMaterialized = ko.observable(false);
            pageMgr.loadModelModule('service-clients/scripts/Northwind/models/sets/Product', function (m) {
                self.Products = ko.observable(new m.entitySet(data.Products));
                self.IsProductsMaterialized(true);
            });
        }
        self.ChangedProducts = ko.observableArray();

        if (data !== null && data.ChangedProducts !== null) {
            pageMgr.loadModelModule('service-clients/scripts/Northwind/models/sets/Product', function (m) {
                for (var i = 0; i < data.ChangedProducts.length; i++) {
                    self.ChangedProducts.push(new m.entityView(data.ChangedProducts[i]));
                }
                self.IsAllProductsMaterialized(true);
            });
        }

        self.MaterializeProducts = function () {
            if (self.IsProductsMaterialized()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/MaterializeProducts",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ entity: self.shallowDataCopy() })
            }).pipe(
                function (dset) {
                    if (dset !== null) {
                        self.data.Products = dset;
                        pageMgr.loadModelModule('service-clients/scripts/Northwind/models/sets/Product', function (m) {
                            var s = new m.entitySet();
                            s.set = dset;
                            s.TotalEntities(dset.EntityCount);
                            s.CurrentSorters(new q.TokenOptions());
                            for (var i = 0; i < dset.Sorters.length; i++)
                                s.CurrentSorters().Options.push(dset.Sorters[i]);
                            s.CurrentSorters().CanBeClosed = true;
                            s.CurrentSorters().isLocal = false;
                            self.Products(s);
                            self.IsProductsMaterialized(true);
                        });
                    }
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.MaterializeAllProducts = function () {
            if (self.IsAllProductsMaterialized()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/MaterializeAllProducts",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ entity: self.shallowDataCopy() })
            }).pipe(
                function (list) {
                    if (list !== null) {
                        self.data.ChangedProducts = list;
                        pageMgr.loadModelModule('service-clients/scripts/Northwind/models/sets/Product', function (m) {
                            for (var i = 0; i < list.length; i++) {
                                self.ChangedProducts.push(new m.entityView(list[i]));
                            }
                            self.IsAllProductsMaterialized(true);
                        });
                    }
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.shallowDataCopy = function() {
            return {
                CategoryID: self.data.CategoryID,
                CategoryName: self.data.CategoryName,
                Description: self.data.Description,
                Picture: self.data.Picture
            };
        };

        self.IsEntitySelected = ko.observable(false);
    };

    var Category = function (data) {
        var self = this;
        self.IsViewModel = false;
        self.TobeLoadMsg = ko.observable('to be loaded ...');
        self.Initializing = true;
        self.data = data;
        self.IsPersisted = ko.observable(data !== null);
        self.IsNewAddition = ko.observable(false);
        self.UpdateIndex = -1;
        self.DistinctString = ko.observable(data !== null ? data.DistinctString : "");
        self.LookupQuery = data !== null ? "entityedit?CategoryID=" + self.data.CategoryID : "";

        self.CreateSet = function () {
            return new CategorySet();
        };

        self.CategoryID = data.CategoryID;
        self.CategoryName = data.CategoryName;
        self.Description = ko.observable(data !== null ? data.Description : null);
        self.IsDescriptionModified = ko.observable(data !== null ? data.IsDescriptionModified : true);
        self.Description.subscribe(function (val) {
             if (!self.Initializing) {
                 if (self.data == null) {
                     self.IsDescriptionModified(true);
                 } else if (self.IsDescriptionLoaded()) {
                     self.IsDescriptionModified(self.data.Description !== val);
                 }
             }
         });
        self.DescriptionCss = ko.pureComputed(function () {
            if (self.IsDescriptionModified()) {
                return "modified";
            } else {
                return "original";
            }
        });
        self.IsDescriptionLoaded = ko.observable(data !== null ? data.IsDescriptionLoaded : true);
        self.LoadEntityDescription = function () {
            if (self.IsDescriptionLoaded()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/LoadEntityDescription",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID })
            }).pipe(
                function (data) {
                    if (data !== null) {
                        self.Initializing = true;
                        self.Description(data);
                        self.Initializing = false;
                    }
                    self.IsDescriptionLoaded(true);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.UpdateEntityDescription = function () {
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/UpdateEntityDescription",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID, data: self.Description() })
            }).pipe(
                function (content) {
                    self.data.Description = self.Description();
                    self.IsDescriptionModified(false);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.Picture = ko.observable(data !== null ? data.Picture : null);
        self.IsPictureModified = ko.observable(data !== null ? data.IsPictureModified : true);
        self.Picture.subscribe(function (val) {
             if (!self.Initializing) {
                 if (self.data == null) {
                     self.IsPictureModified(true);
                 } else if (self.IsPictureLoaded()) {
                     self.IsPictureModified(self.data.Picture !== val);
                 }
             }
         });
        self.PictureCss = ko.pureComputed(function () {
            if (self.IsPictureModified()) {
                return "modified";
            } else {
                return "original";
            }
        });
        self.IsPictureLoaded = ko.observable(data !== null ? data.IsPictureLoaded : true);
        self.LoadEntityPicture = function () {
            if (self.IsPictureLoaded()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/LoadEntityPicture",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID })
            }).pipe(
                function (data) {
                    if (data !== null) {
                        self.Initializing = true;
                        self.Picture(data);
                        self.Initializing = false;
                    }
                    self.IsPictureLoaded(true);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.UpdateEntityPicture = function () {
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/UpdateEntityPicture",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ _CategoryID: self.data.CategoryID, data: self.Picture() })
            }).pipe(
                function (content) {
                    self.data.Picture = self.Picture();
                    self.IsPictureModified(false);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.DescriptionQuery = 'load-delayed-Description?CategoryID=' + self.data.CategoryID + '&contentType=text/plain';

        self.PictureQuery = 'load-delayed-Picture?CategoryID=' + self.data.CategoryID + '&contentType=image/bmp';

        self.IsEntityChanged = ko.observable(false);

        self.IfEntityChanged = ko.pureComputed(function () {
            return self.IsDescriptionModified() || self.IsPictureModified();
        });

        self.IsEntityModified = function () {
            return self.IsDescriptionModified() || self.IsPictureModified();
        }

        self.IsEntityComplete = function () {
            return self.CategoryName !== null;
        };

        self.IsEntityIdentical = function (data) {
            if (typeof data == 'undefined' || data == null || typeof data.IsViewModel == 'undefined' || self.IsViewModel !== data.IsViewModel ) {
                return false;
            }
            return self.CategoryID() == data.CategoryID();
        };

        self.GetUpdatedData = function () {
            if (self.data == null) {
                return self.GetNewData();
            }
            var d = self.NewDataCopy();
            if (self.IsDescriptionModified() || self.IsPictureModified()) {
                if (self.IsDescriptionModified()) {
                    d.Description = self.Description();
                    d.IsDescriptionModified = true;
                    d.IsDescriptionLoaded = self.IsDescriptionLoaded();;
                }
                if (self.IsPictureModified()) {
                    d.Picture = self.Picture();
                    d.IsPictureModified = true;
                    d.IsPictureLoaded = self.IsPictureLoaded();;
                }
                d.IsEntityChanged = true;
                return d;
            } else {
                return null;
            }
        };

        self.GetNewData = function () {
            if (self.CategoryName == null) {
                throw "CategoryName is required!";
            }    
            var d = {
                "CategoryName": self.CategoryName,
                "Description": self.Description(),
                "IsDescriptionModified": true,
                "Picture": self.Picture(),
                "IsPictureModified": true,
                "IsEntityChanged": true,
                "IsPersisted": false
            };
            return d;
        };

        self.NewDataCopy = function () {
            var d = {
                "CategoryID": self.data.CategoryID,
                "CategoryName": self.data.CategoryName,
                "Description": self.data.Description,
                "IsDescriptionModified": self.IsDescriptionModified(),
                "Picture": self.data.Picture,
                "IsPictureModified": self.IsPictureModified(),
                "IsEntityChanged": self.data.IsEntityChanged,
                "IsPersisted": self.data.IsPersisted
            };
            return d;
        };

        self.UpdateData = function (dsrc) {
            if (self.data == null ) {
                return;
            }
            self.data.Description = dsrc.Description;
            self.Description(dsrc.Description);
            self.IsDescriptionModified(false);
            self.data.Picture = dsrc.Picture;
            self.Picture(dsrc.Picture);
            self.IsPictureModified(false);
        };

        self.ResetData = function () {
            if (self.data == null ) {
                return;
            }
            if (self.IsDescriptionModified()) {
                self.Description(self.data.Description);
            }
            if (self.IsPictureModified()) {
                self.Picture(self.data.Picture);
            }
        };

        self.shallowDataCopy = function() {
            return {
                CategoryID: self.data.CategoryID,
                CategoryName: self.data.CategoryName,
                Description: self.data.Description,
                Picture: self.data.Picture
            };
        }

        self.IsProductsMaterialized = ko.observable(data == null);

        self.Products = ko.observable(data !== null ? data.Products : null);

        self.MaterializeProducts = function () {
            if (self.IsProductsMaterialized()) {
                return $.Deferred().resolve();
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/MaterializeProducts",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ entity: self.shallowDataCopy() })
            }).pipe(
                function (dset) {
                    if (dset !== null) {
                        self.data.Products = dset;
                        pageMgr.loadModelModule('service-clients/scripts/Northwind/models/sets/Product', function (m) {
                            var s = new m.entitySet();
                            s.set = dset;
                            s.TotalEntities(dset.EntityCount);
                            s.CurrentSorters(new q.TokenOptions());
                            for (var i = 0; i < dset.Sorters.length; i++)
                                s.CurrentSorters().Options.push(dset.Sorters[i]);
                            s.CurrentSorters().CanBeClosed = true;
                            s.CurrentSorters().isLocal = false;
                            self.Products(s);
                            self.IsProductsMaterialized(true);
                        });
                    }
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.IsEntitySelected = ko.observable(false);
        self.Initializing = false;
    };

    var CategoryPage = function (s, edit) {
        var self = this;
        var editPage = edit;
        self.set = s;
        self.Index_ = ko.observable();
        self.PageNumber = ko.pureComputed(function () {
            return self.Index_() + 1;
        });
        self.FirstItem = ko.observable({});
        self.LastItem = ko.observable({});
        self.CurrentItem = ko.observable(null);
        self.IsLastPage = ko.observable(false);
        self.IsDataLoaded = ko.observable(false);
        self.IsPageSelected = ko.observable(false);
        self.Items =  ko.observableArray([]);
        self.GetPageItems = function (s, pageLoader) {
            if (self.IsDataLoaded()) 
                return $.Deferred().resolve();
            var qexpr = s.getQueryExpr();
            var lastItem = null;
            var ipage = self.Index_();
            if (self.Index_() > 0) {
                var blk = s.PageBlocks()[s.CurrBlockIndex()];
                if (blk.Pages()[0].Index_() !== ipage) {
                    for (var i = 0; i < blk.Pages().length; i++) {
                        if (blk.Pages()[i].Index_() == ipage - 1) {
                            lastItem = blk.Pages()[i].LastItem();
                            break;
                        }
                    }
                } else {
                    var prvb = s.PageBlocks()[s.CurrBlockIndex() - 1];
                    lastItem = prvb.Pages()[prvb.Pages().length - 1].LastItem();
                }
            }
            self.Items.removeAll();
            if (typeof pageLoader !== 'function') {
                return $.ajax({
                    url: config.baseUrl + "/services/Northwind/CategorySet/GetPageItems",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ set: s.set, qexpr: qexpr, prevlast: lastItem })
                }).pipe(
                    function (items) {
                        for (var i = 0; i < items.length; i++) {
                            if (editPage)
                                self.Items.push(new Category(items[i]));
                            else
                                self.Items.push(new CategoryView(items[i]));
                        }
                        self.IsDataLoaded(true);
                        return $.Deferred().resolve();
                    },
                    function (jqxhr, textStatus, error) {
                        return $.Deferred().reject(jqxhr, textStatus, error);
                    }
                );
            } else {
                return pageLoader(self, { set: s.set, qexpr: qexpr, prevlast: lastItem });
            }
        };
    };

    var CategoryPageBlock = function (s, idx0, data, edit) {
        var self = this;
        var set = s;
        self.BlockIndex = ko.observable(0);
        self.BlockNumber = ko.pureComputed(function () { return self.BlockIndex() + 1; });
        self.IsBlockSelected = ko.pureComputed(function() {
            return set.CurrBlockIndex() == self.BlockIndex();
        });
        self.IsLastBlock = ko.observable(data.IsLastBlock);
        self.BlockCount = data.BlockCount;
        self.Pages = ko.observableArray([]);
        if (data.Pages) {
            for (var i = 0; i < data.Pages.length; i++ ) {
                var pdata = data.Pages[i];
                var page = new CategoryPage(s, edit);
                page.Index_(idx0 + pdata.Index_);
                page.FirstItem(pdata.FirstItem);
                page.LastItem(pdata.LastItem);
                page.IsLastPage(pdata.IsLastPage);
                self.Pages.push(page);
            }
        }
        self.LastPage = function () {
            return self.Pages().length == 0 ? null : self.Pages()[self.Pages().length - 1];
        };
    }

    var CategorySettings = function (settings) {
        var self = this;
        self.data = settings || {};
        self.data.show_CategoryID = self.data.show_CategoryID || true;
        self.show_CategoryID = ko.observable(self.data.show_CategoryID);
        self.show_CategoryID.subscribe(function (v) {
            self.data.show_CategoryID = v;
        });
        self.data.collapse_CategoryID = self.data.collapse_CategoryID || false;
        self.collapse_CategoryID = ko.observable(self.data.collapse_CategoryID);
        self.collapse_CategoryID.subscribe(function (v) {
            self.data.collapse_CategoryID = v;
        });
        self.data.width_CategoryID = self.data.width_CategoryID || 'auto';
        self.width_CategoryID = ko.observable(self.data.width_CategoryID);
        self.width_CategoryID.subscribe(function (v) {
            self.data.width_CategoryID = v;
        });
        self.data.show_CategoryName = self.data.show_CategoryName || true;
        self.show_CategoryName = ko.observable(self.data.show_CategoryName);
        self.show_CategoryName.subscribe(function (v) {
            self.data.show_CategoryName = v;
        });
        self.data.collapse_CategoryName = self.data.collapse_CategoryName || false;
        self.collapse_CategoryName = ko.observable(self.data.collapse_CategoryName);
        self.collapse_CategoryName.subscribe(function (v) {
            self.data.collapse_CategoryName = v;
        });
        self.data.width_CategoryName = self.data.width_CategoryName || 'auto';
        self.width_CategoryName = ko.observable(self.data.width_CategoryName);
        self.width_CategoryName.subscribe(function (v) {
            self.data.width_CategoryName = v;
        });
        self.data.show_Description = self.data.show_Description || true;
        self.show_Description = ko.observable(self.data.show_Description);
        self.show_Description.subscribe(function (v) {
            self.data.show_Description = v;
        });
        self.data.collapse_Description = self.data.collapse_Description || true;
        self.collapse_Description = ko.observable(self.data.collapse_Description);
        self.collapse_Description.subscribe(function (v) {
            self.data.collapse_Description = v;
        });
        self.data.width_Description = self.data.width_Description || '';
        self.width_Description = ko.observable(self.data.width_Description);
        self.width_Description.subscribe(function (v) {
            self.data.width_Description = v;
        });
        self.data.show_Picture = self.data.show_Picture || true;
        self.show_Picture = ko.observable(self.data.show_Picture);
        self.show_Picture.subscribe(function (v) {
            self.data.show_Picture = v;
        });
        self.data.collapse_Picture = self.data.collapse_Picture || true;
        self.collapse_Picture = ko.observable(self.data.collapse_Picture);
        self.collapse_Picture.subscribe(function (v) {
            self.data.collapse_Picture = v;
        });
        self.data.width_Picture = self.data.width_Picture || '';
        self.width_Picture = ko.observable(self.data.width_Picture);
        self.width_Picture.subscribe(function (v) {
            self.data.width_Picture = v;
        });
    };

    var CategorySet = function () {
        var self = this;
        self.set = {};

        var jsonstr = localStorage.getItem('Northwind');
        if (typeof jsonstr == 'undefined' || jsonstr == null) {
            self.settings = new CategorySettings();
            var settings = { };
            settings.UIView = { };
            settings.UIView.CategorySet = self.settings.data;
            localStorage.setItem('Northwind', JSON.stringify(settings));
        } else {
            var settings = JSON.parse(jsonstr);
            self.settings = new CategorySettings(settings.UIView.CategorySet);
        }

        self.PageSize_ = ko.observable(config.defaultPageSize);
        self.PageWindowSize = ko.observable(config.defaultPageBlockSize);
        self.PageBlockSize = ko.observable(config.defaultPageBlockSize);
        self.SetKindName = "Table";
        self.EntityName = "Category";
        self.TotalEntities = ko.observable(0);
        self.EntityCount = ko.observable(0);
        self.PageCount = ko.observable(0);
        self.PagesWindow = ko.observableArray([]);
        self.CurrentPage = ko.observable({});
        self.IsQueryStateChanged = ko.observable(false);
        self.BaseUrl = "";
        self.CurrentSorters = ko.observable(null);
        self.CurrentFilters = ko.observable(null);
        self.SortersStack = [];
        self.FiltersStack = [];
        self.SorterPath = ko.observableArray();
        self.FilterPath = ko.observableArray();
        self.PageBlocks = ko.observableArray([]);
        self.CurrBlockIndex = ko.observable(0);
        self.CurrentBlock = ko.pureComputed(function () {
            if (self.CurrBlockIndex() < 0 || self.CurrBlockIndex() >= self.PageBlocks().length - 1)
                return null;
            else
                return self.PageBlocks()[self.CurrBlockIndex()];
        });
        self.PrevBlock = ko.pureComputed(function () {
            var idx = self.CurrBlockIndex();
            if (idx > 0) {
                return self.PageBlocks()[idx - 1];
            } else {
                return null;
            }
        });
        self.NextLoadedBlock = ko.pureComputed(function () {
            var idx = self.CurrBlockIndex();
            if (idx >= 0 && idx < self.PageBlocks().length - 1) {
                return self.PageBlocks()[idx + 1];
            } else {
                return null;
            }
        });
        self.MoreNextBlock = ko.pureComputed(function () {
            var idx = self.CurrBlockIndex();
            if (idx >= 0 && idx < self.PageBlocks().length - 1) {
                return true;
            } else {
                return self.PageBlocks().length > 0 && !self.PageBlocks()[self.PageBlocks().length - 1].IsLastBlock();
            }
        });
        self.LastPageBlock = ko.pureComputed(function () {
            return self.PageBlocks().length == 0 ? null : self.PageBlocks()[self.PageBlocks().length - 1];
        });

        self.ResetPageState = function () {
            self.CurrBlockIndex(0);
            self.PageBlocks.removeAll();
            self.IsQueryStateChanged(false)
        };

        self.IsFilteredView = ko.observable(false);

        self.HasFilteredView = ko.pureComputed(function () {
            return self.CurrentFilters() !== null && self.FilterClosed();
        });

        self.FilteredViewUrl = ko.pureComputed(function () {
            if (self.CurrentFilters() == null || !self.FilterClosed()) {
                return null;
            }
            var s0 = '';
            var bsf = self.set !== null && typeof self.set.SetFilter !== 'undefined' && self.set.SetFilter !== null && self.set.SetFilter !== '';
            if (bsf)
                s0 = '( ' + self.set.SetFilter + ' )';
            var s = '';
            for (var i = 0; i < self.FilterPath().length; i++ ) {
                s += (s == '' ? '' : ' ') + self.FilterPath()[i].TkName;
            }
            if (s == '') {
                return null;
            } else {
                if (s0 == '') {
                    return 'CategorySet?filter=' + encodeURIComponent(s);
                } else {
                    return 'CategorySet?filter=' + encodeURIComponent(s0 + ' && ( ' + s + ' )');
                }
            }
        });

        self.FilteredEditUrl = ko.pureComputed(function () {
            if (self.CurrentFilters() == null || !self.FilterClosed()) {
                return null;
            }
            var s0 = '';
            var bsf = self.set !== null && typeof self.set.SetFilter !== 'undefined' && self.set.SetFilter !== null && self.set.SetFilter !== '';
            if (bsf)
                s0 = '( ' + self.set.SetFilter + ' )';
            var s = '';
            for (var i = 0; i < self.FilterPath().length; i++ ) {
                s += (s == '' ? '' : ' ') + self.FilterPath()[i].TkName;
            }
            if (s == '') {
                return null;
            } else {
                if (s0 == '') {
                    return 'CategorySet?filter=' + encodeURIComponent(s);
                } else {
                    return 'CategorySet?filter=' + encodeURIComponent(s0 + ' && ( ' + s + ' )');
                }
            }
        });

        self.FilterClosed = ko.observable(false);

        self.preSetQExpr = undefined;

        self.RefreshSetState = function(qc) {
            self.IsQueryStateChanged(true);
            self.ResetPageState();
            self.PagesWindow.removeAll();
            if (typeof self.CurrentPage().Items !== 'undefined')
                self.CurrentPage().Items.removeAll();
        };

        self.GetSetInfo = function (tkfilter, _filter) {
            self.BaseUrl = config.baseUrl;
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/GetSetInfo",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ filter: _filter == null ? null : decodeURIComponent(_filter) })
            }).pipe(
                function (content) {
                    self.set = content;
                    self.IsFilteredView(typeof _filter !== 'undefined' && _filter !== null && _filter !== '');
                    self.TotalEntities(self.set.EntityCount);
                    self.CurrentSorters(new q.TokenOptions());
                    for (var i = 0; i < self.set.Sorters.length; i++) {
                        var tk = new q.QToken();
                        tk.CopyToken(self.set.Sorters[i]);
                        if (tkfilter(tk, false)) {
                            self.CurrentSorters().Options.push(tk);
                        }
                    }
                    self.CurrentSorters().CanBeClosed = true;
                    self.CurrentSorters().isLocal = false;
                    return $.Deferred().resolve(self);
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.getQueryExpr = function () {
            if (self.preSetQExpr)
                return self.preSetQExpr;
            var sorters = [];
            var filters = [];
            for (var i = 0; i < self.SorterPath().length; i++)
                sorters.push(self.SorterPath()[i]);
            for (var i = 0; i < self.FilterPath().length; i++)
                filters.push(self.FilterPath()[i]);
            return new q.QueryExpression(sorters, filters);
        };

        self.GetNextSorterOps = function (tkfilter) {
            var qtokens = [];
            for (var i = 0; i < self.SorterPath().length; i++)
                qtokens.push(self.SorterPath()[i]);
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/GetNextSorterOps",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ sorters: qtokens  })
            }).pipe(
                function (content) {
                    self.SortersStack.push(self.CurrentSorters());
                    self.CurrentSorters(new q.TokenOptions());
                    self.CurrentSorters().Hint = content.Hint;
                    self.CurrentSorters().CurrentExpr(content.CurrentExpr);
                    self.CurrentSorters().QuoteVal = content.QuoteVal;
                    self.CurrentSorters().CanBeClosed = content.CanBeClosed;
                    self.CurrentSorters().IsLocal = false;
                    for (var i = 0; i < content.Options.length; i++) {
                        var tk = new q.QToken();
                        tk.CopyToken(content.Options[i]);
                        if (tkfilter(tk, false)) {
                            self.CurrentSorters().Options.push(tk);
                        }
                    }
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.GetNextFilterOps = function (tkfilter) {
            var sorters = [];
            var filters = [];
            for (var i = 0; i < self.SorterPath().length; i++)
                sorters.push(self.SorterPath()[i]);
            for (var i = 0; i < self.FilterPath().length; i++)
                filters.push(self.FilterPath()[i]);
            var qexpr = new q.QueryExpression(sorters, filters);
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/GetNextFilterOps",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ qexpr: qexpr, tkstr: ""  })
            }).pipe(
                function (content) {
                    if (self.CurrentFilters() !== null)
                        self.FiltersStack.push(self.CurrentFilters());
                    self.FilterClosed(content.CanBeClosed);
                    self.CurrentFilters(new q.TokenOptions());
                    self.CurrentFilters().Hint = content.Hint;
                        self.CurrentFilters().CurrentExpr(content.CurrentExpr);
                    self.CurrentFilters().QuoteVal = content.QuoteVal;
                    self.CurrentFilters().CanBeClosed = content.CanBeClosed;
                    self.CurrentFilters().IsLocal = false;
                    for (var i = 0; i < content.Options.length; i++) {
                        var tk = new q.QToken();
                        tk.CopyToken(content.Options[i]);
                        if (tkfilter(tk, true)) {
                            self.CurrentFilters().Options.push(tk);
                        }
                    }
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.NextPageBlock = function (qexpr, last, edit) {
            if (self.IsQueryStateChanged())
                self.ResetPageState();
            if (self.CurrBlockIndex() < self.PageBlocks().length) {
                return $.Deferred().resolve();
            }
            self.set.PageBlockSize = self.PageBlockSize();
            self.set.PageSize_ = self.PageSize_();
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/NextPageBlock",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ set: self.set, qexpr: qexpr, prevlast: last  })
            }).pipe(
                function (data) {
                    if (last == null) 
                        self.EntityCount(data.TotalEntities);
                    self.PageCount(data.TotalPages);
                    if (data.Pages.length == 0) {
                        var lpb = self.LastPageBlock();
                        if (lpb !== null) {
                            lpb.IsLastBlock(true);
                            var lp = lpb.LastPage();
                            if (lp !== null) {
                                lp.IsLastPage(true);
                                self.CurrBlockIndex(self.CurrBlockIndex() - 1);
                            }
                        } else {
                            self.PagesWindow.removeAll();
                        }
                    }
                    else {
                        var idx0 = 0;
                        for (var i = 0; i < self.CurrBlockIndex(); i++ ) {
                            idx0 += self.PageBlocks()[i].BlockCount;
                        }
                        var pb = new CategoryPageBlock(self, idx0, data, edit);
                        pb.BlockIndex(self.PageBlocks().length);
                        self.PageBlocks.push(pb);
                        self.PagesWindow.removeAll();
                        for (var i = 0; i < pb.Pages().length; i++) {
                            self.PagesWindow.push(pb.Pages()[i]);
                        }
                    }
                    self.IsQueryStateChanged(false);
                    return $.Deferred().resolve();
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.AddOrUpdateEntities = function (changed) {
            if (changed == null || changed.length == 0) {
                return $.Deferred().resolve(null);
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/AddOrUpdateEntities",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ set: self.set, entities: changed })
            }).pipe(
                function (data) {
                    //...
                    return $.Deferred().resolve(data);
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.DeleteEntities = function (deleted) {
            if (deleted == null || deleted.length == 0) {
                return $.Deferred().resolve(null);
            }
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/DeleteEntities",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ set: self.set, entities: deleted })
            }).pipe(
                function (data) {
                    //..
                    return $.Deferred().resolve(data);
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

        self.LoadEntityByKey = function(CategoryID, isView) {
            return $.ajax({
                url: config.baseUrl + "/services/Northwind/CategorySet/LoadEntityByKey",
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ CategoryID: CategoryID })
            }).pipe(
                function (data) {
                    if (isView)
                        return $.Deferred().resolve(new CategoryView(data));
                    else
                        return $.Deferred().resolve(new Category(data));
                },
                function (jqxhr, textStatus, error) {
                    return $.Deferred().reject(jqxhr, textStatus, error);
                }
            );
        };

    }

    return {
        entityView: CategoryView,
        entityEdit: Category,
        entityPage: CategoryPage,
        entityPageBlock: CategoryPageBlock,
        settings: CategorySettings,
        entitySet: CategorySet
    }
})